version: '3.7'
services:
  api:
    build: 
      dockerfile: Dockerfile
    #command: uvicorn app.main:app --reload 
    ports:
      - "8080:8080"
    #env_file:
    #  - .env
    #volumes:
    #  - ./:/api
#volumes:
#  appdata:
#    driver: local
